### ISSUE TITLE
Points don't reflect live game counts

### ISSUE THREAD

**Issue by travisryan** [mkreiser/ESPN-Fantasy-Football-API#131]
It seems like after a game is over, your points source is finally updated. 

I think you either need to change it, use this other source, or a combination of both if a game is in progress.

The live score for a matchup period is found in the " schedule/(weeknum)/(AwayOrHome)/rosterForMatchupPeriod/appliedStatTotal

FYI

**Comment by nokz** [comment]
I have the same issue as well. The match up scores were updated over night. I noticed the same issue with FantasyPro's GameDay, ESPN matchups were not updated.

**Comment by travisryan** [comment]
I have this working in my own code. I need to figure out how to do a pull request and push. Hopefully Mike can get this added as it's pretty important on gamedays.

**Comment by mkreiser** [comment]
ESPN exposes a `totalPointsLive` attribute only when the matchup is active. Why `totalPoints` is not updated directly, I have no idea. Fix incoming.

**Comment by mkreiser** [comment]
Fixed in #148 and published as `0.14.1`
