### ISSUE TITLE
Client missing from documentation?

### ISSUE THREAD

**Issue by drusteeby** [mkreiser/ESPN-Fantasy-Football-API#153]
In the generated documentation here: http://espn-fantasy-football-api.s3-website.us-east-2.amazonaws.com/

There doesn't seem to be a page for `Client`. As Client is the starting point of any workflow, it makes it difficult to determine what calls to make and what the return signatures are without looking at the source.

**Comment by mkreiser** [comment]
Oh dang. That's my bad.

Fixing in https://github.com/mkreiser/ESPN-Fantasy-Football-API/pull/154. The docs site should redeploy once master is merged.

**Comment by drusteeby** [comment]
No problem, thanks for fixing! Just wanted to make sure the docs were as useful as possible!
