### ISSUE TITLE
Expanding to other fantasy sports

### ISSUE THREAD

**Issue by RLesser** [mkreiser/ESPN-Fantasy-Football-API#156]
Based on [this API response](https://fantasy.espn.com/apis/v3/games/), it seems like extending this tool to other sports would be quite doable. Are there any thoughts/plans for that? I'd be willing work on it if it's of interest.

**Comment by cdismuke90** [comment]
I am also interested in this and willing to help.

**Comment by akosasante** [comment]
I would also be down to contribute to expanding this, particularly for fantasy baseball
