### ISSUE TITLE
Beginner's Help

### ISSUE THREAD

**Issue by gethubguy** [mkreiser/ESPN-Fantasy-Football-API#167]
Hi there,
I'm code informed enough to know that what's been built here is great. However, I don't have the technical skills to understand how to accomplish what I want.

I'm hoping to plug into this data set via a google sheet - all i want to pull in is player data (think biographical information - like DOB, current team, etc...etc...).

However, I don't know if that's possible from what is laid out here and if it is possible, could someone point me to the appropriate documentation so i can see what i need to do.

**Comment by draynur** [comment]
There are some examples in another thread

https://github.com/mkreiser/ESPN-Fantasy-Football-API/issues/128#issuecomment-541353626 
https://github.com/mkreiser/ESPN-Fantasy-Football-API/issues/128#issuecomment-683249684
https://github.com/mkreiser/ESPN-Fantasy-Football-API/issues/128#issuecomment-528991287
