### ISSUE TITLE
Has anyone been able to pull live projected points out of the response?

### ISSUE THREAD

**Issue by VinPropane** [mkreiser/ESPN-Fantasy-Football-API#174]
I have been able to successfully edit this API for my needs by adding new things to pull out of the response. However, I can not seem to get schedule[i].away/home.totalProjectedPointsLive out of the response even though it is there. I'm curious if there is some issue with this particular field.

![image](https://user-images.githubusercontent.com/25494428/93333317-23525a00-f7f1-11ea-94c8-bad2c2c6b2c6.png)

**Comment by jamesshaw1987** [comment]
You need to include the mScoreboard view along with the mMatchupScore view to make the totalProjectedPointsLive data available.

**Comment by billy-ferris** [comment]
> You need to include the mScoreboard view along with the mMatchupScore view to make the totalProjectedPointsLive data available.

can this be added to the current client? @mkreiser - projected scores are pretty useful for most use cases. Pretty quick update.
