### ISSUE TITLE
Question: is the maintainer still active?

### ISSUE THREAD

**Issue by kurtaking** [mkreiser/ESPN-Fantasy-Football-API#216]
👋🏼 I'm checking in to see if the maintainer is still active and would like help getting this repository up-to-date. I am interested in using this API, but there are a lot of dependencies that need to be updated. Thanks!

**Comment by mkreiser** [comment]
Maintainer here. I'm not really active, but I am working on getting this project back into shape again for this season: https://github.com/mkreiser/ESPN-Fantasy-Football-API/tree/im-back. Once my attention runs out on the current set of updates I'd like to make, this project will probably sit for awhile again.

**Comment by kurtaking** [comment]
Do you have any interest in contributions? I am looking for something to do in my free time, but I noticed existing feature requests and open PRs that have yet to receive attention.

**Comment by Thevtok** [comment]
I don't understand where the route

**Comment by mkreiser** [comment]
Added a lot of stuff this weekend, including several contributions from other devs. Happy to look at contributions as they come in, although I will likely only be able to get to them on the weekends.
